version: '3.8'

services:
  api-gateway:
    image: api-gateway:0.0.1
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sport_facilities_backend
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=8909
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  auth-service:
    image: auth-service:0.0.1
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sport_facilities_backend
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=8909
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  facility-service:
    image: facility-service:0.0.1
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sport_facilities_backend
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=8909
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  booking-service:
    image: booking-service:0.0.1
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sport_facilities_backend
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=8909
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine
    container_name: db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8909
      - POSTGRES_DB=sport_facilities_backend